<?php /** @var $block \Magento\Reports\Block\Product\Viewed */?>
<?php if ($items = $block->getRecentlyViewedProducts()): ?>
    <div class="table-wrapper">
        <table class="table-recently-viewed">
            <tr>
                <th scope="col" class="name"><?=  __('Title') ?></th>
                <th scope="col" class="price"><?= __('Price') ?></th>
                <th scope="col" class="sku"><?= __('SKU') ?></th>
                <th scope="col" class="sku"><?= __('View') ?></th>
            </tr>
             <tr>
                <?php foreach ($items as $_item): ?>
                <td class="title"><?= $_item->getName(); ?></td>
                <td class="price"><?= $_item->getPrice(); ?></td>
                <td class="sku"><?= $_item->getSKU(); ?></td>
            </tr>
        </table>
    </div>
    <?php endforeach ?>
<?php endif;?>
